run:
  tests: false
  timeout: 5m

linters-settings:
  cyclop:
    max-complexity: 12
    skip-tests: true
  gofumpt:
    extra-rules: true

linters:
  enable-all: true
  disable:
    - interfacer # deprecated
    - scopelint # deprecated
    - maligned # deprecated
    - golint # deprecated
    - exhaustivestruct # deprecated
    - ifshort # deprecated
    - deadcode # deprecated
    - nosnakecase # deprecated
    - structcheck # deprecated
    - varcheck # deprecated
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - goerr113
    - gomnd
    - ireturn
    - nlreturn
    - varnamelen
    - wrapcheck
    - wsl

issues:
  exclude-use-default: false
